### ISSUE TITLE
Qwiic LED strip from SparkFun

### ISSUE THREAD

**Issue by alan412** [OpenFTC/I2C-Drivers#1]
I didn't do this as a pull request, because I wasn't sure the folder structure you might want but we (Quantum Quacks) are willing to share our code that is an I2C driver for the Qwiic LED strip from Sparkfun:

The code is in its own repo here:
https://github.com/ftc16072/QwiicLEDStrip

If you let me know how you would like the pull request setup, I am happy to fork the repo and make a pull request.

**Comment by Windwoes** [comment]
Hi - yes, I will set up the library structure soon, get back to you :)

**Comment by Windwoes** [comment]
@alan412 Library structure is now set up
